default_language_version:
  python: python3

exclude: |
  ^(
    node_modules/.*
  )$

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        description: This hook makes pretty files.
        entry: prettier --write --ignore-unknown
        language: node
        "types":
          - text
        args: []
        require_serial: false
        additional_dependencies:
          - prettier@4.0.0-alpha.11
        minimum_pre_commit_version: "0"
